(() => {
const U="2026-09-07T09:00:00+03:00";
const A=(id,category,title,summary,source,sourceUrl,publishedAt,x={})=>({id,category,title,summary,subtitle:x.subtitle||summary,body:x.body||[{heading:"מה קרה",paragraphs:[summary]},{heading:"הפרטים המאומתים",paragraphs:[x.detail||"הפרטים נבדקו מול הפרסום המקורי; מידע שלא פורסם במקור אינו מוצג כעובדה."]},{heading:"למה זה חשוב",paragraphs:[x.context||"המשך הסיפור ייבחן מול הודעות רשמיות ונתונים נוספים."]}],facts:x.facts||[],featured:!!x.featured,image:x.image,imageCredit:x.imageCredit,publishedAt,readTime:x.readTime||"3 דקות",source,sourceUrl,secondarySources:x.secondarySources||[]});
const kan={id:"kan-hendel-zalicha-2026-09-06",date:"2026-09-06",publishedDate:"2026-09-06",source:"כאן חדשות · הסקר האחרון",shortSource:"כאן",pollster:"לא פורסם בכתבה הזמינה",scenario:"הנדל וזליכה ברשימה משותפת",fieldworkDate:null,fieldworkEndDate:null,parties:{"ישר!":23,"הליכוד":20,"ביחד":13,"הדמוקרטים":8,"יהדות התורה":8,"ישראל ביתנו":7,"עוצמה יהודית":7,"ש״ס":7,"חד״ש–תע״ל / המשותפת":7,"רע״ם":6,"הציונות הדתית":6,"עמך ישראל":4,"הנדל–זליכה":4},belowThreshold:[{party:"כחול לבן",percent:null},{party:"הציבור החרדי",percent:null}],sourceUrl:"https://www.kan.org.il/lobby/skarim/",verifiedAt:U};
const ch13={id:"channel13-full-2026-09-02",date:"2026-09-02",publishedDate:"2026-09-02",source:"חדשות 13",shortSource:"13",pollster:"המדד, סטט־נט, פרויקט המדגם, אסקריא ו־Hive",scenario:"לאחר האיחודים",fieldworkDate:null,fieldworkEndDate:null,marginOfError:"±3.4%",sampleSize:940,parties:{"ישר!":22,"הליכוד":21,"ביחד":12,"הדמוקרטים":11,"חד״ש–תע״ל / המשותפת":9,"ישראל ביתנו":8,"יהדות התורה":8,"עוצמה יהודית":7,"ש״ס":7,"הציונות הדתית–זהות":6,"רע״ם":5,"עמך ישראל":4},belowThreshold:[{party:"בית ציוני–המילואימניקים",percent:2.2},{party:"כחול לבן",percent:1.2},{party:"האחדות",percent:.6},{party:"הציבור החרדי",percent:.3},{party:"מקום לכולנו",percent:.3},{party:"הכלכלית",percent:.2}],sourceUrl:"https://13tv.co.il/item/news/politics/politics/survey-905340911/",verifiedAt:U};
const walla={id:"walla-union-2026-09-02",date:"2026-09-02",publishedDate:"2026-09-02",source:"וואלה · תרחיש איחוד",shortSource:"וואלה",pollster:"לזר מחקרים · Panel4All",scenario:"איחוד הציונות הדתית וזהות",fieldworkDate:"2026-09-01",fieldworkEndDate:"2026-09-02",marginOfError:"±4.4%",parties:{"ישר!":24,"הליכוד":22,"ביחד":15,"הדמוקרטים":10,"ישראל ביתנו":9,"יהדות התורה":8,"חד״ש–תע״ל / המשותפת":8,"עוצמה יהודית":7,"ש״ס":7,"הציונות הדתית–זהות":5,"רע״ם":5},belowThreshold:[{party:"בית ציוני–המילואימניקים",percent:3},{party:"עמך ישראל",percent:2.3},{party:"הכלכלית",percent:2},{party:"כחול לבן",percent:.7}],sourceUrl:"https://news.walla.co.il/item/3865040",verifiedAt:U};
const articles=[
A("lists-open-0802-20260907","בארץ","היום נפתחת הגשת הרשימות: מערכת הבחירות נכנסת לשלב המחייב","בשעה 13:00 צפויה להתחיל הגשת רשימות המועמדים, חמישים יום לפני ההצבעה.","כיכר השבת","https://www.kikar.co.il/scoop-news","2026-09-07T07:30:00+03:00",{featured:true,detail:"לפי הדיווח, עמך ישראל של עופר וינטר צפויה להגיש רשימה היום, ובליכוד נמשכו דיונים על השריונים.",context:"המסמכים שיימסרו לוועדת הבחירות יקבעו אילו חיבורים אכן יצאו לפועל.",facts:["פתיחת ההגשה: 13:00","50 יום לבחירות","הבחירות: 27 באוקטובר"]}),
A("kan-poll-0802-20260907","בארץ","סקר כאן: 52 לגוש נתניהו, 51 לגוש איזנקוט — ואין רוב","ישר! מקבלת 23 מנדטים, הליכוד 20 וביחד 13; הנדל–זליכה ועמך ישראל עם ארבעה כל אחת.","כאן חדשות","https://www.kan.org.il/lobby/skarim/","2026-09-06T21:30:00+03:00",{featured:true,image:"https://i.kikar.co.il/2026/09/06/2de66580-aa22-11f1-a241-2193649ffc80__h1080_w1920.jpg?width=1400",imageCredit:"איזנקוט ונתניהו · חיים גולדברג ואבשלום ששוני, Flash90",detail:"מלוא 120 המושבים הוזנו למרכז הסקרים. מועדי עבודת השדה וגודל המדגם לא פורסמו בכתבה הזמינה ומסומנים כחסרים.",facts:["גוש נתניהו: 52","גוש איזנקוט: 51","13 לרשימות שאינן משויכות"]}),
A("gaza-ied-response-0900-20260907","בארץ","מטען פגע בכלי הנדסי בצפון הרצועה; צה״ל תקף תשתיות חמאס","לא היו נפגעים לכוחות; צה״ל הגדיר את הפעלת המטען במרחב הקו הצהוב הפרה של הסכם הפסקת האש.","כיכר השבת · הודעת צה״ל","https://www.kikar.co.il/security-news/idf-strikes-gaza-hamas-ceasefire-violation","2026-09-07T07:36:00+03:00",{featured:true,detail:"לפי הודעת דובר צה״ל שצוטטה בדיווח, הכלי נפגע ביום ראשון ובתגובה הותקפו במהלך הלילה תשתיות ששימשו לקידום מתווי טרור.",context:"היקף התקיפות והמשך התגובה ייבחנו מול הודעות רשמיות נוספות; אין להסיק מהאירוע לבדו על שינוי רחב בהסכם.",facts:["אין נפגעים לכוחות","המטען הופעל בצפון הרצועה","התגובה בוצעה במהלך הלילה"]}),
A("heat-wave-0802-20260907","בארץ","החום מתחזק: עד 39 מעלות באילת והכבדה בעומסים","הטמפרטורות עולות בהרים ובפנים הארץ, ומחר צפויה הכבדה נוספת.","כיכר השבת","https://www.kikar.co.il/israel-news/thop0g-44","2026-09-07T07:29:00+03:00",{detail:"התחזית מציינת 28 מעלות בירושלים, 30 בתל אביב, 32 בבאר שבע ו־39 באילת.",facts:["ירושלים 18–28","תל אביב 24–30","אילת 28–39"]}),
A("channel14-ruling-0802-20260907","בארץ","בית המשפט חייב את ערוץ 14 ועיתונאי ב־100 אלף שקל","בית משפט השלום ברחובות קיבל חלקית תביעת לשון הרע על פרסומים מתקופת הקורונה.","כיכר השבת","https://www.kikar.co.il/law-and-order/channel-14-langerman-libel-compensation-ruling","2026-09-07T06:55:00+03:00",{detail:"לפי הדיווח, נקבע כי חלק מהפרסומים היו רשלניים ולא הוכחו; פסק הדין המלא הוא המסמך הקובע.",facts:["פיצוי: 100 אלף שקל","שלום רחובות"]}),
A("selichot-skolen-0802-20260907","חרדים","סליחות ראשונות בסקולען לייקווד: האדמו״ר בטלית הירושה","האדמו״ר עבר לפני התיבה ובסיום עברו החסידים לקבל ברכת שנה טובה.","כיכר השבת","https://www.kikar.co.il/hasidism/tkyik6","2026-09-06T22:22:00+03:00",{image:"https://i.kikar.co.il/2026/09/06/8fc3d090-aa26-11f1-a241-2193649ffc80__h3235_w4826.JPG?width=1400",imageCredit:"סליחות ראשונות בסקולען לייקווד · באדיבות המצלם",detail:"לפי הכתבה, הטלית שבה השתמש האדמו״ר הייתה ירושה מאביו.",facts:["המעמד נערך בלייקווד","ברכת שנה טובה בסיום"]}),
A("hadassah-karlebach-0900-20260907","חרדים","בגיל 99: נפטרה הדסה קרליבך, שסייעה להצלת ילדים בשואה","קרליבך פעלה כנערה לצד אביה בצרפת הכבושה והותירה מורשת של הצלה והנצחה.","כיכר השבת","https://www.kikar.co.il/haredim-news/hadassah-karlebach-holocaust-rescuer","2026-09-07T07:36:00+03:00",{detail:"לפי הדיווח, היא נולדה בלנינגרד, חייתה תחת רדיפות המשטר הסובייטי ולאחר מכן סייעה עם משפחתה למאות ילדים יהודים בצרפת.",context:"הכתבה נסמכת גם על דיווח COLive; נתוני ההצלה מוצגים כייחוס למקורות אלה.",facts:["נפטרה בגיל 99","ניצולת שואה","קרובת משפחת הרבי מליובאוויטש"]}),
A("degel-paper-gafni-maklev-0900-20260907","חרדים","ביטאון דגל התורה: הדחת גפני ומקלב אינה הבעת אי־אמון","יתד נאמן טען שהשניים פעלו לפי הנחיות גדולי ישראל וכי השינוי נועד לרענון השורות.","כיכר השבת","https://www.kikar.co.il/haredim-news/degel-hatorah-responds-gafni-maklev-dismissal","2026-09-07T07:47:00+03:00",{featured:true,image:"https://i.kikar.co.il/2026/09/02/ae52e980-a6a5-11f1-ac42-b37e534359ed__h4385_w6575.jpg?width=1400",imageCredit:"אורי מקלב ומשה גפני · Olivier Fitoussi/Flash90",detail:"הביטאון לא נקב בשמותיהם בגוף ההודעה, וציין שהרכב הרשימה עדיין ממתין לאישור מועצת גדולי התורה.",context:"הנוסח הוא עמדת הביטאון; הרשימה המחייבת תהיה זו שתוגש לוועדת הבחירות.",facts:["הפרסום: 07:47","ממתינים לאישור המועצת"]}),
A("hormuz-ships-0802-20260907","עולם","ארה״ב ואיראן תקפו כלי שיט סביב הורמוז; הנפט מטפס","התקיפות ההדדיות והאטת תנועת המכליות העלו מחדש חשש לשיבוש אספקה ממושך.","Reuters","https://www.reuters.com/business/energy/oil-extends-gains-after-us-iran-strike-ships-2026-09-07/","2026-09-07T07:15:00+03:00",{featured:true,detail:"ארה״ב מסרה שתקפה שלוש מכליות איראניות; משמרות המהפכה אמרו שתקפו שלוש מכליות ושלושה כלי שיט אמריקניים.",facts:["Brent: 96.97$","WTI: 92.24$","כ־10 אוניות סחורה ביום"]}),
A("miami-crash-0802-20260907","עולם","חמישה נהרגו בהתרסקות מטוס מטען במיאמי; תיעוד חדש פורסם","מטוס מטען חרג מהמסלול, פגע בכלי רכב ועלה באש; חמישה נוספים נפצעו.","כיכר השבת","https://www.kikar.co.il/world-news/tkz75k","2026-09-07T07:07:00+03:00",{image:"https://i.kikar.co.il/2026/09/07/0ddfc070-aa71-11f1-a241-2193649ffc80__h1024_w576.jpg?width=900",imageCredit:"זירת התרסקות מטוס המטען במיאמי · תיעוד שפורסם בכיכר השבת",detail:"הרשויות חוקרות את החריגה מהמסלול בנמל התעופה הבינלאומי של מיאמי.",facts:["5 הרוגים","5 פצועים","3 במצב קריטי"]}),
A("krakatau-0802-20260907","עולם","אנאק קראקאטאו התפרץ: אפר עד 15 קילומטרים וברקים בענן","הר הגעש במצר סונדה פלט לבה וענני אפר כבדים; אלפי טיסות הושפעו לפי הדיווח.","כיכר השבת","https://www.kikar.co.il/world-news/tkz7oi","2026-09-07T07:17:00+03:00",{image:"https://i.kikar.co.il/2026/09/07/ec2c5cc0-aa72-11f1-a111-1ba500bd48ff__h568_w320.jpg?width=900",imageCredit:"התפרצות אנאק קראקאטאו · תיעוד שפורסם בכיכר השבת",detail:"ההתפרצות לוותה בפיצוצים ובעמוד אפר שהתקדם לעבר ג׳אווה וסומטרה.",facts:["ענן אפר: עד 15,000 מטר","מצר סונדה"]}),
A("germany-jews-0802-20260907","עולם","שגריר ישראל בגרמניה מזהיר: החיים היהודיים תחת איום","רון פרושאור קרא למעבר מהצהרות לצעדים מעשיים להגנת הקהילות.","כיכר השבת","https://www.kikar.co.il/world-news/israel-ambassador-germany-warns-jewish-life-threat","2026-09-07T06:57:00+03:00",{detail:"השגריר קשר את הדאגה להתפתחויות פוליטיות ולהתחזקות קצוות משני צדי המפה."}),
A("us-mail-vote-0802-20260907","עולם","ממשל טראמפ שוב פונה לעליון להגבלת הצבעה בדואר","הממשל ביקש לאפשר כלל חדש לקראת בחירות האמצע בנובמבר.","Reuters","https://www.reuters.com/legal/government/trump-administration-renews-supreme-court-bid-limit-mail-in-voting-2026-09-06/","2026-09-07T01:20:00+03:00",{detail:"הכלל דורש רשימות מקבלי פתקים וברקוד ייחודי; מבקריו מזהירים מפסילת קולות.",facts:["בחירות: 3 בנובמבר","תגובות עד יום רביעי"]}),
A("oil-rally-0802-20260907","כלכלה","הנפט מטפס והספנות מתייקרת: הורמוז במרכז השווקים","ברנט עלה 0.7% ו־WTI ב־0.8% לנוכח חשש לפגיעה ביצוא.","Reuters","https://www.reuters.com/world/china/global-markets-global-markets-2026-09-07/","2026-09-07T08:35:00+03:00",{detail:"OPEC+ הותירה את מדיניות התפוקה לאוקטובר ללא שינוי; הנתונים עודכנו בפרסום השווקים המאוחר יותר.",facts:["Brent 96.97$","WTI 92.24$","השוק האמריקני סגור היום"]}),
A("ship-fuel-0802-20260907","כלכלה","מחסור בדלק אוניות מתקרב: מלאי הנמלים נמוך בכ־30%","בתי זיקוק מעדיפים דיזל ובנזין והמלחמות פוגעות באספקת מזוט.","Reuters","https://www.reuters.com/business/energy/ship-fuel-shortage-looms-refiners-strained-by-war-favour-other-products-2026-09-07/","2026-09-07T06:40:00+03:00",{detail:"הגירעון החזוי ברבעון השלישי הוא 218 אלף חביות ביום לעומת 6,000 שנה קודם.",facts:["גירעון: 218 אלף חביות ביום","מלאי נמוך בכ־30%"]}),
A("asia-tech-markets-0900-20260907","כלכלה","מניות השבבים הובילו את אסיה; הנפט והתשואות מגבילים את החגיגה","ניקיי עלה 2.2% וקוספי 3.1%, בעוד השווקים ממתינים למדד המחירים האמריקני ביום שישי.","Reuters","https://www.reuters.com/world/china/global-markets-global-markets-2026-09-07/","2026-09-07T04:06:00+03:00",{featured:true,detail:"מדד MSCI לאסיה מחוץ ליפן עלה 1.1%, מדד CSI300 הוסיף 0.2% ותשואת אג״ח ארה״ב לעשר שנים עמדה על 4.7840%.",context:"עליות הטכנולוגיה משקפות אופטימיות לצמיחה, אך נפט יקר וציפיות להעלאות ריבית מוסיפים סיכון לאינפלציה.",facts:["ניקיי +2.2%","קוספי +3.1%","אג״ח ארה״ב 10 שנים: 4.7840%"]}),
A("antonelli-monza-0802-20260907","ספורט","מהמקום ה־19 לניצחון: אנטונלי השלים קאמבק במונזה","קימי אנטונלי ניצח בגרנד פרי איטליה לפני ג׳ורג׳ ראסל ומקס ורסטאפן.","Formula 1","https://www.formula1.com/en/latest/article/antonelli-beats-russell-to-italian-grand-prix-win-with-stunning-comeback-drive.15WtFEBT5JEe4drdeO88t2","2026-09-06T18:20:00+03:00",{featured:true,detail:"האיטלקי זינק מהמקום ה־19 וסיים 3.857 שניות לפני ראסל.",facts:["אנטונלי: 1","ראסל: +3.857","ורסטאפן: +14.718"]}),
A("arsenal-chelsea-0802-20260907","ספורט","ארסנל ניצחה 1:2 את צ׳לסי ועלתה למקום השני","האברץ ואודגור הפכו שער מוקדם של רוג׳רס; ארסנל עם תשע נקודות.","The Guardian","https://www.theguardian.com/football/live/2026/sep/06/arsenal-v-chelsea-premier-league-live","2026-09-06T20:25:00+03:00",{detail:"רוג׳רס כבש בדקה 2, האברץ ב־25 ואודגור ב־50.",facts:["ארסנל 2:1 צ׳לסי","ארסנל: 9 נקודות"]}),
A("everton-united-0802-20260907","ספורט","מייטלנד־ניילס קבע 2:2 דרמטי מול מנצ׳סטר יונייטד","יונייטד הפכה בדקות 83 ו־88, אך אברטון השוותה בתוספת הזמן.","Reuters","https://www.reuters.com/sports/soccer/maitland-niles-screamer-earns-everton-2-2-draw-with-man-utd-2026-09-06/","2026-09-06T22:40:00+03:00",{detail:"מבאומו כבש לאברטון; ג׳ורג׳ וססקו הפכו; מייטלנד־ניילס השווה.",facts:["אברטון 2:2 יונייטד","אברטון 8; יונייטד 11"]}),
A("juve-milan-0802-20260907","ספורט","גאטי חילץ ליובנטוס 1:1 מול מילאן בדקה ה־92","סיסה העלה את מילאן ליתרון בדקה 69 והבלם השווה בתוספת הזמן.","Reuters","https://www.reuters.com/sports/soccer/gatti-rescues-point-juventus-1-1-draw-with-ac-milan-2026-09-06/","2026-09-06T23:55:00+03:00",{detail:"שתי הקבוצות עם שבע נקודות; מילאן מעל יובנטוס בהפרש שערים.",facts:["1:1","סיסה 69; גאטי 92"]}),
A("usopen-0802-20260907","ספורט","אלקראס ושלטון דהרו לרבע הגמר בניו יורק","אלקראס גבר על טומי פול בשלוש מערכות; שלטון עשה זאת מול ציציפאס.","Reuters","https://www.reuters.com/sports/tennis/shelton-stops-tsitsipas-sets-up-alcaraz-showdown-us-open-2026-09-07/","2026-09-07T04:20:00+03:00",{detail:"אלקראס ניצח 6:4, 6:3, 6:4; שלטון 6:2, 6:3, 6:4.",facts:["רבע הגמר: אלקראס–שלטון"]}),
A("guardians-walkoff-0900-20260907","ספורט","קליבלנד ניצחה 2:3 בווקאוף ועלתה למקום הוויילד־קארד האחרון","דניאל שנימן הכניס את ריצת הניצחון באינינג העשירי מול דטרויט.","Reuters","https://www.reuters.com/sports/baseball/guardians-again-notch-walk-off-win-over-tigers--flm-2026-09-06/","2026-09-06T23:50:00+03:00",{detail:"זה היה הווקאוף השלישי של הגרדיאנס בארבעה משחקים; גאווין ויליאמס רשם 11 סטרייקאאוטים והגיע ל־228, המאזן המוביל ב־MLB.",context:"קליבלנד עלתה למאזן 73–71 ופתחה יתרון של משחק על טורונטו במאבק על כרטיס הוויילד־קארד האחרון באמריקן ליג.",facts:["קליבלנד 3:2 דטרויט","10 אינינגים","ויליאמס: 11 סטרייקאאוטים"]}),
A("taiwan-chips-0802-20260907","טכנולוגיה","טייוואן הופכת שבבים לכלי דיפלומטי ומפזרת ייצור","ב־SEMICON הציגה הממשלה את התעשייה כבסיס לשותפות עם ארה״ב ואירופה.","Reuters","https://www.reuters.com/world/china/taiwan-flexes-chip-diplomacy-muscles-it-faces-pressure-share-ai-wealth-with-2026-09-07/","2026-09-07T05:26:00+03:00",{featured:true,detail:"TSMC משקיעה 265 מיליארד דולר באריזונה וחברות מתכננות עוד 20 מיליארד בארה״ב.",facts:["TSMC: 265 מיליארד דולר","תוספת מתוכננת: 20 מיליארד"]}),
A("china-ai-chips-0802-20260907","טכנולוגיה","יצרניות שבבים סיניות מצמצמות פערים מול Nvidia","ניתוח מצביע על התרחבות חלופות מקומיות ולחץ גובר על יתרון Nvidia בסין.","Reuters Breakingviews","https://www.reuters.com/commentary/breakingviews/chinas-ai-dragons-breathe-fire-nvidias-moat-2026-09-07/","2026-09-07T06:10:00+03:00",{detail:"זהו טור ניתוח של Breakingviews ולא ידיעה רגילה; המסקנות מסומנות בהתאם."}),
A("wmo-air-0802-20260907","טכנולוגיה","WMO: אירועי עשן שריפות קיצוניים שולשו מאז שנות התשעים","סוכנות מזג האוויר של האו״ם מזהירה ששריפות וגלי חום פוגעים באיכות האוויר.","Reuters","https://www.reuters.com/sustainability/cop/wildfires-heat-waves-threaten-undermine-air-quality-un-weather-agency-says-2026-09-07/","2026-09-07T07:01:00+03:00",{detail:"הדו״ח מדגיש PM2.5, אוזון ופערי ניטור של פחמן שחור ומיקרופלסטיק.",facts:["אירועי עשן קיצוניים שולשו","כ־100 אלף מקרי מוות נוספים בשנה במחקר המצוטט"]})
];
const analysis=`שלוש התפתחויות נפרדות מסמנות הבוקר את המתח האזורי, אך חשוב לא לחבר ביניהן כאילו היו מהלך אחד. בצפון רצועת עזה נפגע כלי הנדסי של צה״ל ממטען במרחב הקו הצהוב. לא היו נפגעים, וצה״ל מסר כי תקף במהלך הלילה תשתיות חמאס ששימשו לקידום מתווי טרור. זמן קצר לאחר מכן פורסמו הנחיות פינוי לכפר דיר א־זהראני בדרום לבנון. במקביל, סביב מצר הורמוז נמשכו תקיפות הדדיות בין ארה״ב לאיראן, ותנועת המכליות האטה.

אלה זירות שונות, עם שחקנים, כללים ומטרות שונות. המשותף להן הוא דפוס של איתות לפני הסלמה או מיד אחריה. בעזה, הודעת התגובה מבקשת לקבוע שהפעלת המטען אינה אירוע טקטי זניח אלא הפרה של מסגרת הפסקת האש. בלבנון, הוראת פינוי היא קודם כול צעד להגנת אזרחים; היא עשויה להקדים פעולה, אך בעת פרסום המהדורה עדיין אינה הוכחה להיקף התקיפה או אפילו לכך שכבר בוצעה. בהורמוז, כלי השיט עצמם הפכו לזירת לחץ, ולכן גם ירידה בקצב המעבר היא מסר כלכלי ולא רק נתון תפעולי.

מכאן נובע האתגר המרכזי: לכל צד יש אינטרס להציג פעולה מוגבלת כהוכחת נחישות, ובאותה עת להשאיר מרחב שמונע הידרדרות בלתי נשלטת. הצלחה טקטית יכולה להפוך לכישלון אסטרטגי אם הצד השני מפרש אותה כהזמנה לתגובה רחבה יותר. מנגד, היעדר תגובה עלול להיתפס כהסכמה לשינוי כללי המשחק. לכן השאלה החשובה איננה רק מה הותקף, אלא כיצד כל זירה מגדירה את קו הגבול הבא.

ההשלכה על ישראל אינה מסתכמת בממד הצבאי. מחיר ברנט נע סביב 97 דולר לחבית ו־WTI סביב 92 דולר, על רקע החשש לשיבוש מתמשך בהורמוז. נפט יקר יותר יכול להעלות עלויות הובלה, ביטוח ויבוא, גם אם אספקה פיזית ממשיכה להגיע. תשואת אג״ח ארה״ב לעשר שנים עמדה על 4.7840%, והשווקים כבר מתמחרים לחץ אינפלציוני וריביות גבוהות יותר. כלומר, אירוע ימי רחוק יחסית יכול לעבור במהירות לחשבון האנרגיה וליוקר המחיה.

מה צריך לבדוק מכאן? בעזה: האם צה״ל מפרסם פרטים נוספים על יעד התקיפות והאם חמאס מגיב. בלבנון: האם הוראת הפינוי מתרחבת ליישובים נוספים ומה מודיע דובר צה״ל לאחריה. בהורמוז: כמה אוניות עוברות בפועל, האם חברות ספנות משנות מסלול, ומה קורה לתעריפי הביטוח ולמחירי הנפט מעבר לתנודה של שעה אחת. אלה מדדים טובים יותר מכותרות דרמטיות.

הקריאה הזהירה של הבוקר היא שהאזור נמצא במבחן של גבולות, לא בהכרח במלחמה אחודה. כל אחת משלוש הזירות עלולה להישאר מוגבלת, אך הצטברותן מגדילה את הסיכון לטעות בחישוב. לכן הערכת מצב אחראית צריכה להפריד בין עובדה, הודעה רשמית והערכה; לעקוב אחרי רצף פעולות ולא אחרי אירוע יחיד; ולבחון גם את ערוצי התקשורת בין הצדדים. השעות הקרובות ילמדו אם האיתותים יצרו הרתעה נקודתית או מדרגה נוספת בסולם ההסלמה.`;
window.NEWS_FEED={articles,deepDives:[
{id:"deep-regional-signals-0900-20260907",category:"עומק",title:"עזה, לבנון והורמוז: שלושה איתותים, שלושה סולמות הסלמה",summary:"האירועים אינם מהלך אחד, אך הצטברותם מגדילה את מחיר הטעות הצבאית והכלכלית.",subtitle:"כך מפרידים בין עובדות, הודעות ואיומים — ומה יכריע בשעות הקרובות.",body:analysis,author:"עמית רז · פרשן המערכת (שם עט)",source:"ניתוח המערכת",sourceUrl:"https://www.kikar.co.il/security-news/idf-strikes-gaza-hamas-ceasefire-violation",secondarySources:[{name:"כיכר השבת · מבזקי לבנון",url:"https://www.kikar.co.il/scoop-news"},{name:"Reuters · הורמוז ונפט",url:"https://www.reuters.com/business/energy/oil-extends-gains-after-us-iran-strike-ships-2026-09-07/"},{name:"Reuters · תמונת השווקים",url:"https://www.reuters.com/world/china/global-markets-global-markets-2026-09-07/"}],publishedAt:U,readTime:"7 דקות",featured:true,featuredAnalysis:true,wordCount:0},
{id:"deep-hormuz-0802-20260907",category:"עומק",title:"הורמוז חזר להיות מחיר ולא רק מפה",summary:"תקיפות, ירידה בתנועת מכליות ומחסור בדלק אוניות מתחברים ללחץ על האספקה.",body:"העלייה בנפט פוגשת מלאי דלק אוניות נמוכים והעדפה של בתי זיקוק למוצרים רווחיים יותר. השילוב עלול לעבור לתעריפי הובלה ומשם למחירי יבוא. הנתון הקריטי הוא קצב המעבר בפועל במצר.",author:"מערכת החדשות",source:"Reuters",sourceUrl:"https://www.reuters.com/business/energy/oil-extends-gains-after-us-iran-strike-ships-2026-09-07/",secondarySources:[{name:"Reuters · דלק אוניות",url:"https://www.reuters.com/business/energy/ship-fuel-shortage-looms-refiners-strained-by-war-favour-other-products-2026-09-07/"},{name:"Reuters · תמונת השווקים",url:"https://www.reuters.com/world/china/global-markets-global-markets-2026-09-07/"}],publishedAt:U,readTime:"4 דקות"},
{id:"deep-chip-0802-20260907",category:"עומק",title:"שבבים כמטבע מדיני: טייוואן מפזרת סיכון",summary:"ייצור בארה״ב ובאירופה מחזק בריתות אך מעביר השקעות אל מחוץ לאי.",body:"טייוואן משתמשת בכוח הייצור כדי להעמיק קשרים עם דמוקרטיות אחרות. השקעות הענק באריזונה מציעות עמידות, אך יוצרות ויכוח על המקום שבו יישאר הערך המוסף. המבחן יהיה היכן יישארו המחקר, האריזה המתקדמת וכוח האדם.",author:"מערכת החדשות",source:"Reuters",sourceUrl:"https://www.reuters.com/world/china/taiwan-flexes-chip-diplomacy-muscles-it-faces-pressure-share-ai-wealth-with-2026-09-07/",secondarySources:[{name:"Reuters Breakingviews · שבבי AI בסין",url:"https://www.reuters.com/commentary/breakingviews/chinas-ai-dragons-breathe-fire-nvidias-moat-2026-09-07/"},{name:"TSMC · פעילות עולמית",url:"https://www.tsmc.com/english/aboutTSMC"}],publishedAt:U,readTime:"4 דקות"}
],markets:[
{symbol:"SPX",name:"S&P 500",value:"7,718.60",change:"−0.38% · −29.11",direction:"down",status:"סגירת 04.09 · סגור היום",note:"תעסוקה חזקה הגבירה ציפיות להעלאת ריבית",source:"Reuters",sourceUrl:"https://www.reuters.com/business/nasdaq-sp-500-futures-climb-ahead-key-jobs-report-2026-09-04/",updatedAt:U},
{symbol:"IXIC",name:"Nasdaq",value:"26,506.99",change:"−0.29% · −77.07",direction:"down",status:"סגירת 04.09",note:"לחץ מעליית תשואות",source:"Reuters",sourceUrl:"https://www.reuters.com/business/nasdaq-sp-500-futures-climb-ahead-key-jobs-report-2026-09-04/",updatedAt:U},
{symbol:"DJI",name:"Dow Jones",value:"53,414.25",change:"−0.51% · −271.86",direction:"down",status:"סגירת 04.09",note:"לחץ רוחבי לאחר דוח התעסוקה",source:"Reuters",sourceUrl:"https://www.reuters.com/business/nasdaq-sp-500-futures-climb-ahead-key-jobs-report-2026-09-04/",updatedAt:U},
{symbol:"RUT",name:"Russell 2000",value:"2,975.65",change:"+0.25% · +7.38",direction:"up",status:"סגירת 04.09",note:"מניות קטנות סיימו בעלייה",source:"נתוני שוק",sourceUrl:"https://www.google.com/finance/quote/RUT:INDEXRUSSELL",updatedAt:U},
{symbol:"VIX",name:"VIX",value:"14.53",change:"+1.47% · +0.21",direction:"up",status:"סגירת 04.09",note:"עלייה מתונה בביקוש להגנה",source:"Cboe",sourceUrl:"https://www.cboe.com/tradable-products/vix/",updatedAt:U},
{symbol:"CL",name:"WTI",value:"$92.24",change:"+0.80% · כ־+$0.73",direction:"up",status:"מסחר 07.09 · 04:06",note:"הסלמה סביב הורמוז",source:"Reuters",sourceUrl:"https://www.reuters.com/world/china/global-markets-global-markets-2026-09-07/",updatedAt:U},
{symbol:"BZ",name:"Brent",value:"$96.97",change:"+0.70% · כ־+$0.67",direction:"up",status:"מסחר 07.09 · 04:06",note:"חשש לשיבוש יצוא",source:"Reuters",sourceUrl:"https://www.reuters.com/world/china/global-markets-global-markets-2026-09-07/",updatedAt:U},
{symbol:"XAU",name:"זהב",value:"$4,406.00",change:"−0.50% · כ־−$22.1",direction:"down",status:"ספוט 07.09 · 04:06",note:"התשואות הגבוהות לחצו על המתכת",source:"Reuters",sourceUrl:"https://www.reuters.com/world/china/global-markets-global-markets-2026-09-07/",updatedAt:U},
{symbol:"BTC",name:"Bitcoin",value:"$79,748",change:"−0.26% · −$204",direction:"down",status:"רציף · 09:00",note:"סביב 80 אלף",source:"נתוני שוק",sourceUrl:"https://www.google.com/finance/quote/BTC-USD",updatedAt:U},
{symbol:"ETH",name:"Ethereum",value:"$2,504.49",change:"−0.26% · −$6.65",direction:"down",status:"רציף · 09:00",note:"ירידה קלה",source:"נתוני שוק",sourceUrl:"https://www.google.com/finance/quote/ETH-USD",updatedAt:U}
],meta:{updatedAt:U,locale:"he-IL",edition:"מהדורת בוקר · עזה, לבנון, הורמוז ושווקים",contentPolicy:"מהדורת היום הוחלפה במלואה ב־08:02; עדכון 09:00 מחליף פריטים שהתיישנו ושומר רק תוכן שנבדק מחדש"},polls:[kan,ch13,walla],scores:[
{id:"guardians-tigers-20260906-final",league:"MLB",dateLabel:"06.09",teams:["קליבלנד גארדיאנס","דטרויט טייגרס"],score:["3","2"],state:"final",status:"סופי · 10 אינינגים",outcome:"ווקאוף שלישי בארבעה משחקים",scorers:"דניאל שנימן הכניס את ריצת הניצחון",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/baseball/guardians-again-notch-walk-off-win-over-tigers--flm-2026-09-06/",winner:"home",verifiedAt:U,verifiedLabel:"אומת 09:00"},
{id:"f1-monza-20260906-final",league:"פורמולה 1",dateLabel:"06.09",teams:["קימי אנטונלי","ג׳ורג׳ ראסל"],score:["1","2"],state:"final",status:"סופי",outcome:"אנטונלי זינק 19 וניצח",scorers:"פער 3.857 שניות",source:"Formula 1",sourceUrl:"https://www.formula1.com/en/latest/article/antonelli-beats-russell-to-italian-grand-prix-win-with-stunning-comeback-drive.15WtFEBT5JEe4drdeO88t2",winner:"home",verifiedAt:U,verifiedLabel:"אומת 09:00"},
{id:"arsenal-chelsea-20260906-final",league:"פרמייר ליג",dateLabel:"06.09",teams:["ארסנל","צ׳לסי"],score:["2","1"],state:"final",status:"סופי",scorers:"האברץ 25, אודגור 50; רוג׳רס 2",source:"The Guardian",sourceUrl:"https://www.theguardian.com/football/live/2026/sep/06/arsenal-v-chelsea-premier-league-live",winner:"home",verifiedAt:U,verifiedLabel:"אומת 09:00"},
{id:"everton-united-20260906-final",league:"פרמייר ליג",dateLabel:"06.09",teams:["אברטון","מנצ׳סטר יונייטד"],score:["2","2"],state:"final",status:"סופי",outcome:"שוויון בתוספת הזמן",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/soccer/maitland-niles-screamer-earns-everton-2-2-draw-with-man-utd-2026-09-06/",winner:"draw",verifiedAt:U,verifiedLabel:"אומת 09:00"},
{id:"juve-milan-20260906-final",league:"סרייה א׳",dateLabel:"06.09",teams:["יובנטוס","מילאן"],score:["1","1"],state:"final",status:"סופי",scorers:"גאטי 92; סיסה 69",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/soccer/gatti-rescues-point-juventus-1-1-draw-with-ac-milan-2026-09-06/",winner:"draw",verifiedAt:U,verifiedLabel:"אומת 09:00"},
{id:"mainz-hamburg-20260906-final",league:"בונדסליגה",dateLabel:"06.09",teams:["מיינץ","המבורג"],score:["5","0"],state:"final",status:"סופי",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/soccer/mainz-thrash-hamburg-augsburg-go-top-with-win-frankfurt-2026-09-06/",winner:"home",verifiedAt:U,verifiedLabel:"אומת 09:00"},
{id:"alcaraz-paul-20260906-final",league:"US Open",dateLabel:"06.09",teams:["קרלוס אלקראס","טומי פול"],score:["3","0"],state:"final",status:"סופי",scorers:"6:4, 6:3, 6:4",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/tennis/alcaraz-outguns-paul-reach-us-open-quarter-finals-2026-09-06/",winner:"home",verifiedAt:U,verifiedLabel:"אומת 09:00"},
{id:"shelton-tsitsipas-20260906-final",league:"US Open",dateLabel:"06.09",teams:["בן שלטון","סטפנוס ציציפאס"],score:["3","0"],state:"final",status:"סופי",scorers:"6:2, 6:3, 6:4",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/tennis/shelton-stops-tsitsipas-sets-up-alcaraz-showdown-us-open-2026-09-07/",winner:"home",verifiedAt:U,verifiedLabel:"אומת 09:00"},
{id:"redsox-orioles-20260906-final",league:"MLB",dateLabel:"06.09",teams:["בוסטון רד סוקס","בולטימור אוריולס"],score:["3","1"],state:"final",status:"סופי",outcome:"שמירה 400 לצ׳פמן",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/baseball/aroldis-chapman-earns-400th-save-as-red-sox-sweep-orioles--flm-2026-09-06/",winner:"home",verifiedAt:U,verifiedLabel:"אומת 09:00"}
],socialPulse:[],videos:[]};
window.NEWS_FEED.deepDives[0].wordCount=analysis.trim().split(/\s+/).length;
})();
