(() => {
const U="2026-09-07T08:02:00+03:00";
const A=(id,category,title,summary,source,sourceUrl,publishedAt,x={})=>({id,category,title,summary,subtitle:x.subtitle||summary,body:x.body||[{heading:"מה קרה",paragraphs:[summary]},{heading:"הפרטים המאומתים",paragraphs:[x.detail||"הפרטים נבדקו מול הפרסום המקורי; מידע שלא פורסם במקור אינו מוצג כעובדה."]},{heading:"למה זה חשוב",paragraphs:[x.context||"המשך הסיפור ייבחן מול הודעות רשמיות ונתונים נוספים."]}],facts:x.facts||[],featured:!!x.featured,image:x.image,imageCredit:x.imageCredit,publishedAt,readTime:x.readTime||"3 דקות",source,sourceUrl,secondarySources:x.secondarySources||[]});
const kan={id:"kan-hendel-zalicha-2026-09-06",date:"2026-09-06",publishedDate:"2026-09-06",source:"כאן חדשות · הסקר האחרון",shortSource:"כאן",pollster:"לא פורסם בכתבה הזמינה",scenario:"הנדל וזליכה ברשימה משותפת",fieldworkDate:null,fieldworkEndDate:null,parties:{"ישר!":23,"הליכוד":20,"ביחד":13,"הדמוקרטים":8,"יהדות התורה":8,"ישראל ביתנו":7,"עוצמה יהודית":7,"ש״ס":7,"חד״ש–תע״ל / המשותפת":7,"רע״ם":6,"הציונות הדתית":6,"עמך ישראל":4,"הנדל–זליכה":4},belowThreshold:[{party:"כחול לבן",percent:null},{party:"הציבור החרדי",percent:null}],sourceUrl:"https://www.kan.org.il/lobby/skarim/",verifiedAt:U};
const ch13={id:"channel13-full-2026-09-02",date:"2026-09-02",publishedDate:"2026-09-02",source:"חדשות 13",shortSource:"13",pollster:"המדד, סטט־נט, פרויקט המדגם, אסקריא ו־Hive",scenario:"לאחר האיחודים",fieldworkDate:null,fieldworkEndDate:null,marginOfError:"±3.4%",sampleSize:940,parties:{"ישר!":22,"הליכוד":21,"ביחד":12,"הדמוקרטים":11,"חד״ש–תע״ל / המשותפת":9,"ישראל ביתנו":8,"יהדות התורה":8,"עוצמה יהודית":7,"ש״ס":7,"הציונות הדתית–זהות":6,"רע״ם":5,"עמך ישראל":4},belowThreshold:[{party:"בית ציוני–המילואימניקים",percent:2.2},{party:"כחול לבן",percent:1.2},{party:"האחדות",percent:.6},{party:"הציבור החרדי",percent:.3},{party:"מקום לכולנו",percent:.3},{party:"הכלכלית",percent:.2}],sourceUrl:"https://13tv.co.il/item/news/politics/politics/survey-905340911/",verifiedAt:U};
const walla={id:"walla-union-2026-09-02",date:"2026-09-02",publishedDate:"2026-09-02",source:"וואלה · תרחיש איחוד",shortSource:"וואלה",pollster:"לזר מחקרים · Panel4All",scenario:"איחוד הציונות הדתית וזהות",fieldworkDate:"2026-09-01",fieldworkEndDate:"2026-09-02",marginOfError:"±4.4%",parties:{"ישר!":24,"הליכוד":22,"ביחד":15,"הדמוקרטים":10,"ישראל ביתנו":9,"יהדות התורה":8,"חד״ש–תע״ל / המשותפת":8,"עוצמה יהודית":7,"ש״ס":7,"הציונות הדתית–זהות":5,"רע״ם":5},belowThreshold:[{party:"בית ציוני–המילואימניקים",percent:3},{party:"עמך ישראל",percent:2.3},{party:"הכלכלית",percent:2},{party:"כחול לבן",percent:.7}],sourceUrl:"https://news.walla.co.il/item/3865040",verifiedAt:U};
const articles=[
A("lists-open-0802-20260907","בארץ","היום נפתחת הגשת הרשימות: מערכת הבחירות נכנסת לשלב המחייב","בשעה 13:00 צפויה להתחיל הגשת רשימות המועמדים, חמישים יום לפני ההצבעה.","כיכר השבת","https://www.kikar.co.il/scoop-news","2026-09-07T07:30:00+03:00",{featured:true,detail:"לפי הדיווח, עמך ישראל של עופר וינטר צפויה להגיש רשימה היום, ובליכוד נמשכו דיונים על השריונים.",context:"המסמכים שיימסרו לוועדת הבחירות יקבעו אילו חיבורים אכן יצאו לפועל.",facts:["פתיחת ההגשה: 13:00","50 יום לבחירות","הבחירות: 27 באוקטובר"]}),
A("kan-poll-0802-20260907","בארץ","סקר כאן: 52 לגוש נתניהו, 51 לגוש איזנקוט — ואין רוב","ישר! מקבלת 23 מנדטים, הליכוד 20 וביחד 13; הנדל–זליכה ועמך ישראל עם ארבעה כל אחת.","כאן חדשות","https://www.kan.org.il/lobby/skarim/","2026-09-06T21:30:00+03:00",{featured:true,image:"https://i.kikar.co.il/2026/09/06/2de66580-aa22-11f1-a241-2193649ffc80__h1080_w1920.jpg?width=1400",imageCredit:"איזנקוט ונתניהו · חיים גולדברג ואבשלום ששוני, Flash90",detail:"מלוא 120 המושבים הוזנו למרכז הסקרים. מועדי עבודת השדה וגודל המדגם לא פורסמו בכתבה הזמינה ומסומנים כחסרים.",facts:["גוש נתניהו: 52","גוש איזנקוט: 51","13 לרשימות שאינן משויכות"]}),
A("gaza-strike-0802-20260907","בארץ","צה״ל: התקיפה בעזה כוונה לפעיל חמאס; דווח על הרוגים","צה״ל מסר כי תקף פעיל חמאס ובוחן את התוצאה; גורמי רפואה דיווחו על ארבעה הרוגים ביום ראשון.","Reuters","https://www.reuters.com/world/middle-east/israeli-strike-kills-two-people-gaza-medics-say-2026-09-06/","2026-09-07T00:10:00+03:00",{detail:"רויטרס ציינה כי הפסקת האש מאוקטובר 2025 עדיין מסגרת מדינית, אך שני הצדדים מאשימים בהפרות.",facts:["צה״ל: היעד היה פעיל חמאס","דיווחי רפואה: ארבעה הרוגים"]}),
A("heat-wave-0802-20260907","בארץ","החום מתחזק: עד 39 מעלות באילת והכבדה בעומסים","הטמפרטורות עולות בהרים ובפנים הארץ, ומחר צפויה הכבדה נוספת.","כיכר השבת","https://www.kikar.co.il/israel-news/thop0g-44","2026-09-07T07:29:00+03:00",{detail:"התחזית מציינת 28 מעלות בירושלים, 30 בתל אביב, 32 בבאר שבע ו־39 באילת.",facts:["ירושלים 18–28","תל אביב 24–30","אילת 28–39"]}),
A("channel14-ruling-0802-20260907","בארץ","בית המשפט חייב את ערוץ 14 ועיתונאי ב־100 אלף שקל","בית משפט השלום ברחובות קיבל חלקית תביעת לשון הרע על פרסומים מתקופת הקורונה.","כיכר השבת","https://www.kikar.co.il/law-and-order/channel-14-langerman-libel-compensation-ruling","2026-09-07T06:55:00+03:00",{detail:"לפי הדיווח, נקבע כי חלק מהפרסומים היו רשלניים ולא הוכחו; פסק הדין המלא הוא המסמך הקובע.",facts:["פיצוי: 100 אלף שקל","שלום רחובות"]}),
A("selichot-skolen-0802-20260907","חרדים","סליחות ראשונות בסקולען לייקווד: האדמו״ר בטלית הירושה","האדמו״ר עבר לפני התיבה ובסיום עברו החסידים לקבל ברכת שנה טובה.","כיכר השבת","https://www.kikar.co.il/hasidism/tkyik6","2026-09-06T22:22:00+03:00",{image:"https://i.kikar.co.il/2026/09/06/8fc3d090-aa26-11f1-a241-2193649ffc80__h3235_w4826.JPG?width=1400",imageCredit:"סליחות ראשונות בסקולען לייקווד · באדיבות המצלם",detail:"לפי הכתבה, הטלית שבה השתמש האדמו״ר הייתה ירושה מאביו.",facts:["המעמד נערך בלייקווד","ברכת שנה טובה בסיום"]}),
A("breslov-reflection-0802-20260907","חרדים","חשבון נפש בלי ייאוש: שיחת עומק על ברסלב","ר׳ מרדכי גרנביץ הציג תפיסה שלפיה מציאת נקודות טובות היא בסיס לעבודה עצמית.","כיכר השבת","https://www.kikar.co.il/service-of-the-heart/breslov-self-reflection-rosh-hashanah","2026-09-06T20:00:00+03:00",{detail:"השיחה עוסקת במתח שבין ביקורת עצמית לאמון בטוב ובמשמעות הנסיעה לאומן.",facts:["ראיון באורך 36:42","לקראת ראש השנה"]}),
A("haredi-list-shakeup-0802-20260907","חרדים","מאבקי הרגע האחרון ברשימות החרדיות לקראת ההגשה","דיווחים במגזר מצביעים על בחינת חילופי נציגים בדגל התורה ובאגודת ישראל.","כיכר השבת","https://www.kikar.co.il/haredim-news/tkxzjb","2026-09-06T18:29:00+03:00",{detail:"הדיווחים מתארים אפשרויות ולא רשימה חתומה; ההרכב הסופי יתברר במסמכי ההגשה."}),
A("hormuz-ships-0802-20260907","עולם","ארה״ב ואיראן תקפו כלי שיט סביב הורמוז; הנפט מטפס","התקיפות ההדדיות והאטת תנועת המכליות העלו מחדש חשש לשיבוש אספקה ממושך.","Reuters","https://www.reuters.com/business/energy/oil-extends-gains-after-us-iran-strike-ships-2026-09-07/","2026-09-07T07:15:00+03:00",{featured:true,detail:"ארה״ב מסרה שתקפה שלוש מכליות איראניות; משמרות המהפכה אמרו שתקפו שלוש מכליות ושלושה כלי שיט אמריקניים.",facts:["Brent: 97.07$","WTI: 92.28$","כ־10 אוניות סחורה ביום"]}),
A("miami-crash-0802-20260907","עולם","חמישה נהרגו בהתרסקות מטוס מטען במיאמי; תיעוד חדש פורסם","מטוס מטען חרג מהמסלול, פגע בכלי רכב ועלה באש; חמישה נוספים נפצעו.","כיכר השבת","https://www.kikar.co.il/world-news/tkz75k","2026-09-07T07:07:00+03:00",{image:"https://i.kikar.co.il/2026/09/07/0ddfc070-aa71-11f1-a241-2193649ffc80__h1024_w576.jpg?width=900",imageCredit:"זירת התרסקות מטוס המטען במיאמי · תיעוד שפורסם בכיכר השבת",detail:"הרשויות חוקרות את החריגה מהמסלול בנמל התעופה הבינלאומי של מיאמי.",facts:["5 הרוגים","5 פצועים","3 במצב קריטי"]}),
A("krakatau-0802-20260907","עולם","אנאק קראקאטאו התפרץ: אפר עד 15 קילומטרים וברקים בענן","הר הגעש במצר סונדה פלט לבה וענני אפר כבדים; אלפי טיסות הושפעו לפי הדיווח.","כיכר השבת","https://www.kikar.co.il/world-news/tkz7oi","2026-09-07T07:17:00+03:00",{image:"https://i.kikar.co.il/2026/09/07/ec2c5cc0-aa72-11f1-a111-1ba500bd48ff__h568_w320.jpg?width=900",imageCredit:"התפרצות אנאק קראקאטאו · תיעוד שפורסם בכיכר השבת",detail:"ההתפרצות לוותה בפיצוצים ובעמוד אפר שהתקדם לעבר ג׳אווה וסומטרה.",facts:["ענן אפר: עד 15,000 מטר","מצר סונדה"]}),
A("germany-jews-0802-20260907","עולם","שגריר ישראל בגרמניה מזהיר: החיים היהודיים תחת איום","רון פרושאור קרא למעבר מהצהרות לצעדים מעשיים להגנת הקהילות.","כיכר השבת","https://www.kikar.co.il/world-news/israel-ambassador-germany-warns-jewish-life-threat","2026-09-07T06:57:00+03:00",{detail:"השגריר קשר את הדאגה להתפתחויות פוליטיות ולהתחזקות קצוות משני צדי המפה."}),
A("us-mail-vote-0802-20260907","עולם","ממשל טראמפ שוב פונה לעליון להגבלת הצבעה בדואר","הממשל ביקש לאפשר כלל חדש לקראת בחירות האמצע בנובמבר.","Reuters","https://www.reuters.com/legal/government/trump-administration-renews-supreme-court-bid-limit-mail-in-voting-2026-09-06/","2026-09-07T01:20:00+03:00",{detail:"הכלל דורש רשימות מקבלי פתקים וברקוד ייחודי; מבקריו מזהירים מפסילת קולות.",facts:["בחירות: 3 בנובמבר","תגובות עד יום רביעי"]}),
A("oil-rally-0802-20260907","כלכלה","הנפט מטפס והספנות מתייקרת: הורמוז במרכז השווקים","ברנט עלה 0.82% ו־WTI ב־0.87% לנוכח חשש לפגיעה ביצוא.","Reuters","https://www.reuters.com/business/energy/oil-extends-gains-after-us-iran-strike-ships-2026-09-07/","2026-09-07T07:15:00+03:00",{detail:"OPEC+ הותירה את מדיניות התפוקה לאוקטובר ללא שינוי.",facts:["Brent 97.07$","WTI 92.28$","ברנט +7.8% בשבוע"]}),
A("ship-fuel-0802-20260907","כלכלה","מחסור בדלק אוניות מתקרב: מלאי הנמלים נמוך בכ־30%","בתי זיקוק מעדיפים דיזל ובנזין והמלחמות פוגעות באספקת מזוט.","Reuters","https://www.reuters.com/business/energy/ship-fuel-shortage-looms-refiners-strained-by-war-favour-other-products-2026-09-07/","2026-09-07T06:40:00+03:00",{detail:"הגירעון החזוי ברבעון השלישי הוא 218 אלף חביות ביום לעומת 6,000 שנה קודם.",facts:["גירעון: 218 אלף חביות ביום","מלאי נמוך בכ־30%"]}),
A("wallstreet-close-0802-20260907","כלכלה","וול סטריט ירדה; היום אין מסחר בארה״ב בשל יום העבודה","S&P 500 ירד 0.38%, נאסד״ק 0.29% ודאו 0.51% ביום שישי.","Reuters","https://www.reuters.com/business/nasdaq-sp-500-futures-climb-ahead-key-jobs-report-2026-09-04/","2026-09-05T00:15:00+03:00",{detail:"תעסוקה חזקה חיזקה ציפיות להעלאת ריבית; הבורסות סגורות היום.",facts:["S&P: 7,718.60","Nasdaq: 26,506.99","Dow: 53,414.25"]}),
A("antonelli-monza-0802-20260907","ספורט","מהמקום ה־19 לניצחון: אנטונלי השלים קאמבק במונזה","קימי אנטונלי ניצח בגרנד פרי איטליה לפני ג׳ורג׳ ראסל ומקס ורסטאפן.","Formula 1","https://www.formula1.com/en/latest/article/antonelli-beats-russell-to-italian-grand-prix-win-with-stunning-comeback-drive.15WtFEBT5JEe4drdeO88t2","2026-09-06T18:20:00+03:00",{featured:true,detail:"האיטלקי זינק מהמקום ה־19 וסיים 3.857 שניות לפני ראסל.",facts:["אנטונלי: 1","ראסל: +3.857","ורסטאפן: +14.718"]}),
A("arsenal-chelsea-0802-20260907","ספורט","ארסנל ניצחה 1:2 את צ׳לסי ועלתה למקום השני","האברץ ואודגור הפכו שער מוקדם של רוג׳רס; ארסנל עם תשע נקודות.","The Guardian","https://www.theguardian.com/football/live/2026/sep/06/arsenal-v-chelsea-premier-league-live","2026-09-06T20:25:00+03:00",{detail:"רוג׳רס כבש בדקה 2, האברץ ב־25 ואודגור ב־50.",facts:["ארסנל 2:1 צ׳לסי","ארסנל: 9 נקודות"]}),
A("everton-united-0802-20260907","ספורט","מייטלנד־ניילס קבע 2:2 דרמטי מול מנצ׳סטר יונייטד","יונייטד הפכה בדקות 83 ו־88, אך אברטון השוותה בתוספת הזמן.","Reuters","https://www.reuters.com/sports/soccer/maitland-niles-screamer-earns-everton-2-2-draw-with-man-utd-2026-09-06/","2026-09-06T22:40:00+03:00",{detail:"מבאומו כבש לאברטון; ג׳ורג׳ וססקו הפכו; מייטלנד־ניילס השווה.",facts:["אברטון 2:2 יונייטד","אברטון 8; יונייטד 11"]}),
A("juve-milan-0802-20260907","ספורט","גאטי חילץ ליובנטוס 1:1 מול מילאן בדקה ה־92","סיסה העלה את מילאן ליתרון בדקה 69 והבלם השווה בתוספת הזמן.","Reuters","https://www.reuters.com/sports/soccer/gatti-rescues-point-juventus-1-1-draw-with-ac-milan-2026-09-06/","2026-09-06T23:55:00+03:00",{detail:"שתי הקבוצות עם שבע נקודות; מילאן מעל יובנטוס בהפרש שערים.",facts:["1:1","סיסה 69; גאטי 92"]}),
A("usopen-0802-20260907","ספורט","אלקראס ושלטון דהרו לרבע הגמר בניו יורק","אלקראס גבר על טומי פול בשלוש מערכות; שלטון עשה זאת מול ציציפאס.","Reuters","https://www.reuters.com/sports/tennis/shelton-stops-tsitsipas-sets-up-alcaraz-showdown-us-open-2026-09-07/","2026-09-07T04:20:00+03:00",{detail:"אלקראס ניצח 6:4, 6:3, 6:4; שלטון 6:2, 6:3, 6:4.",facts:["רבע הגמר: אלקראס–שלטון"]}),
A("chapman400-0802-20260907","ספורט","צ׳פמן הגיע ל־400 שמירות; בוסטון השלימה סוויפ","הרד סוקס ניצחו 1:3 את בולטימור וצ׳פמן הפך לתשיעי בתולדות MLB בציון הדרך.","Reuters","https://www.reuters.com/sports/baseball/aroldis-chapman-earns-400th-save-as-red-sox-sweep-orioles--flm-2026-09-06/","2026-09-07T02:10:00+03:00",{facts:["בוסטון 3:1 בולטימור","400 שמירות"]}),
A("taiwan-chips-0802-20260907","טכנולוגיה","טייוואן הופכת שבבים לכלי דיפלומטי ומפזרת ייצור","ב־SEMICON הציגה הממשלה את התעשייה כבסיס לשותפות עם ארה״ב ואירופה.","Reuters","https://www.reuters.com/world/china/taiwan-flexes-chip-diplomacy-muscles-it-faces-pressure-share-ai-wealth-with-2026-09-07/","2026-09-07T05:26:00+03:00",{featured:true,detail:"TSMC משקיעה 265 מיליארד דולר באריזונה וחברות מתכננות עוד 20 מיליארד בארה״ב.",facts:["TSMC: 265 מיליארד דולר","תוספת מתוכננת: 20 מיליארד"]}),
A("china-ai-chips-0802-20260907","טכנולוגיה","יצרניות שבבים סיניות מצמצמות פערים מול Nvidia","ניתוח מצביע על התרחבות חלופות מקומיות ולחץ גובר על יתרון Nvidia בסין.","Reuters Breakingviews","https://www.reuters.com/commentary/breakingviews/chinas-ai-dragons-breathe-fire-nvidias-moat-2026-09-07/","2026-09-07T06:10:00+03:00",{detail:"זהו טור ניתוח של Breakingviews ולא ידיעה רגילה; המסקנות מסומנות בהתאם."}),
A("wmo-air-0802-20260907","טכנולוגיה","WMO: אירועי עשן שריפות קיצוניים שולשו מאז שנות התשעים","סוכנות מזג האוויר של האו״ם מזהירה ששריפות וגלי חום פוגעים באיכות האוויר.","Reuters","https://www.reuters.com/sustainability/cop/wildfires-heat-waves-threaten-undermine-air-quality-un-weather-agency-says-2026-09-07/","2026-09-07T07:01:00+03:00",{detail:"הדו״ח מדגיש PM2.5, אוזון ופערי ניטור של פחמן שחור ומיקרופלסטיק.",facts:["אירועי עשן קיצוניים שולשו","כ־100 אלף מקרי מוות נוספים בשנה במחקר המצוטט"]})
];
const analysis=`העובדה הבסיסית של הבוקר פשוטה: היום מתחילה הגשת רשימות המועמדים, ובתוך שעות יהפכו חלק גדול מהשמועות הפוליטיות למסמכים מחייבים. במקביל, סקר כאן חדשות שפורסם אמש מעניק 23 מנדטים לישר! של גדי איזנקוט, 20 לליכוד ו־13 לביחד. לפי חלוקת הגושים שפורסמה, גוש נתניהו עומד על 52 וגוש איזנקוט על 51. רשימת הנדל–זליכה ועמך ישראל מקבלות ארבעה מנדטים כל אחת, ורע״ם שישה. אין כאן רוב, ויש כאן הרבה מאוד כוח לרשימות קטנות.

השינוי החשוב לעומת הסקר הקודם איננו רק יתרון של מנדט לגוש אחד. הוא נובע מכניסה של רשימה חדשה מעל אחוז החסימה ומהסידור מחדש של המגרש. כאשר כמה מפלגות נמצאות סביב ארבעה מנדטים, כל תזוזה זעירה יכולה למחוק רשימה, להעביר קולות לאיבוד ולשנות את חלוקת המושבים בין כל האחרות. לכן סקר ערב הגשת הרשימות הוא צילום של מערכת שעדיין זזה, לא תחזית סופית.

צריך גם לקרוא את המספרים בזהירות. הפרסום הזמין מציג חלוקה מלאה של 120 מושבים, ולכן אפשר להזין אותה למרכז הסקרים. עם זאת, הוא אינו מפרסם את מועדי עבודת השדה, את גודל המדגם או את שיעורי התמיכה המדויקים במפלגות שמתחת לסף. החוסרים האלה אינם מבטלים את הסקר, אבל הם מצמצמים את היכולת להשוות אותו באופן נקי למדידות אחרות. משום כך מרכז הסקרים מציג גם את תאריך הפרסום וגם סימון מפורש למידע שלא פורסם.

המשמעות הפוליטית היא כפולה. ראשית, המפלגות הגדולות צריכות לבחור בין משיכת קולות מהשותפות שלהן לבין הגנה עליהן מפני נפילה. קמפיין אגרסיבי מדי בתוך הגוש עלול להגדיל מפלגה אחת אך להקטין את הגוש כולו. שנית, הרשימות שאינן משויכות בבירור לאחד המחנות עשויות להפוך לציר המשא ומתן לאחר הבחירות, אבל רק אם יעברו בפועל את אחוז החסימה.

מועד ההגשה יבהיר מי רץ עם מי, אילו שמות שובצו במקומות ריאליים ואילו איחודים נשארו על הנייר. אחריו יהיה אפשר להשוות סקרים על בסיס רשימות יציבות יותר. עד אז, עדיף להתמקד בשלושה דברים: האם רשימות ארבעת המנדטים נשארות מעל הסף בכמה מכונים שונים; האם הפער בין הגושים חוזר ביותר מסקר אחד; והאם שיעור המתלבטים משתנה לאחר פרסום הרשימות.

המסקנה אינה שמישהו ניצח הבוקר. המסקנה היא שהמערכת עברה משלב ההצהרות לשלב המבני. מסמכי ההגשה יקבעו את האפשרויות, הסקרים הבאים ימדדו את תגובת הציבור, ורק רצף מדידות לאחר סגירת הרשימות יאפשר לומר אם מדובר במהפך או בתנודה רגעית. גם אז, צריך לזכור שמנדטים בסקר הם אומדן ולא תוצאה, ושקואליציה נבנית מהסכמות בין מפלגות ולא רק מסכום מתמטי. יום ההגשה הוא נקודת התחלה טובה יותר למדידה, אך עדיין לא קו הסיום. לכן המבחן של השבוע הקרוב יהיה עקביות: האם מכונים שונים, עם שיטות שונות ובימים שונים, יראו אותה מגמה. אם כן, יהיה בסיס לדבר על שינוי. אם לא, הסקר האחרון יישאר בעיקר תזכורת לרגישות של המפה לאחוז החסימה.`;
window.NEWS_FEED={articles,deepDives:[
{id:"deep-lists-0802-20260907",category:"עומק",title:"יום הגשת הרשימות: הסקר משנה את הלחץ — לא את המתמטיקה",summary:"הגושים כמעט שווים, אבל רשימות הסף ומידע מתודולוגי חסר מחייבים זהירות.",subtitle:"מה אפשר ללמוד מסקר כאן ומה יתברר רק אחרי ההגשה.",body:analysis,author:"נועם ארז · פרשן המערכת (שם עט)",source:"ניתוח המערכת",sourceUrl:"https://www.kan.org.il/lobby/skarim/",secondarySources:[{name:"כיכר השבת · הסקר",url:"https://www.kikar.co.il/israel-news/tkygq8"},{name:"ועדת הבחירות",url:"https://www.gov.il/he/departments/units/central-elections-committee/govil-landing-page"}],publishedAt:U,readTime:"7 דקות",featured:true,featuredAnalysis:true,wordCount:0},
{id:"deep-hormuz-0802-20260907",category:"עומק",title:"הורמוז חזר להיות מחיר ולא רק מפה",summary:"תקיפות, ירידה בתנועת מכליות ומחסור בדלק אוניות מתחברים ללחץ על האספקה.",body:"העלייה בנפט פוגשת מלאי דלק אוניות נמוכים והעדפה של בתי זיקוק למוצרים רווחיים יותר. השילוב עלול לעבור לתעריפי הובלה ומשם למחירי יבוא. הנתון הקריטי הוא קצב המעבר בפועל במצר.",author:"מערכת החדשות",source:"Reuters",sourceUrl:"https://www.reuters.com/business/energy/oil-extends-gains-after-us-iran-strike-ships-2026-09-07/",publishedAt:U,readTime:"4 דקות"},
{id:"deep-chip-0802-20260907",category:"עומק",title:"שבבים כמטבע מדיני: טייוואן מפזרת סיכון",summary:"ייצור בארה״ב ובאירופה מחזק בריתות אך מעביר השקעות אל מחוץ לאי.",body:"טייוואן משתמשת בכוח הייצור כדי להעמיק קשרים עם דמוקרטיות אחרות. השקעות הענק באריזונה מציעות עמידות, אך יוצרות ויכוח על המקום שבו יישאר הערך המוסף. המבחן יהיה היכן יישארו המחקר, האריזה המתקדמת וכוח האדם.",author:"מערכת החדשות",source:"Reuters",sourceUrl:"https://www.reuters.com/world/china/taiwan-flexes-chip-diplomacy-muscles-it-faces-pressure-share-ai-wealth-with-2026-09-07/",publishedAt:U,readTime:"4 דקות"}
],markets:[
{symbol:"SPX",name:"S&P 500",value:"7,718.60",change:"−0.38% · −29.11",direction:"down",status:"סגירת 04.09 · סגור היום",note:"תעסוקה חזקה הגבירה ציפיות להעלאת ריבית",source:"Reuters",sourceUrl:"https://www.reuters.com/business/nasdaq-sp-500-futures-climb-ahead-key-jobs-report-2026-09-04/",updatedAt:U},
{symbol:"IXIC",name:"Nasdaq",value:"26,506.99",change:"−0.29% · −77.07",direction:"down",status:"סגירת 04.09",note:"לחץ מעליית תשואות",source:"Reuters",sourceUrl:"https://www.reuters.com/business/nasdaq-sp-500-futures-climb-ahead-key-jobs-report-2026-09-04/",updatedAt:U},
{symbol:"DJI",name:"Dow Jones",value:"53,414.25",change:"−0.51% · −271.86",direction:"down",status:"סגירת 04.09",note:"לחץ רוחבי לאחר דוח התעסוקה",source:"Reuters",sourceUrl:"https://www.reuters.com/business/nasdaq-sp-500-futures-climb-ahead-key-jobs-report-2026-09-04/",updatedAt:U},
{symbol:"RUT",name:"Russell 2000",value:"2,975.65",change:"+0.25% · +7.38",direction:"up",status:"סגירת 04.09",note:"מניות קטנות סיימו בעלייה",source:"נתוני שוק",sourceUrl:"https://www.google.com/finance/quote/RUT:INDEXRUSSELL",updatedAt:U},
{symbol:"VIX",name:"VIX",value:"14.53",change:"+1.47% · +0.21",direction:"up",status:"סגירת 04.09",note:"עלייה מתונה בביקוש להגנה",source:"Cboe",sourceUrl:"https://www.cboe.com/tradable-products/vix/",updatedAt:U},
{symbol:"CL",name:"WTI",value:"$92.28",change:"+0.87% · +$0.80",direction:"up",status:"מסחר 07.09 · 08:12",note:"הסלמה סביב הורמוז",source:"Reuters",sourceUrl:"https://www.reuters.com/business/energy/oil-extends-gains-after-us-iran-strike-ships-2026-09-07/",updatedAt:U},
{symbol:"BZ",name:"Brent",value:"$97.07",change:"+0.82% · +$0.79",direction:"up",status:"מסחר 07.09 · 08:12",note:"חשש לשיבוש יצוא",source:"Reuters",sourceUrl:"https://www.reuters.com/business/energy/oil-extends-gains-after-us-iran-strike-ships-2026-09-07/",updatedAt:U},
{symbol:"XAU",name:"זהב",value:"$4,402.86",change:"−0.60% · כ־−$26.6",direction:"down",status:"ספוט 07.09 · 08:05",note:"תשואות גבוהות",source:"Reuters",sourceUrl:"https://www.reuters.com/world/india/gold-eases-robust-us-payrolls-boost-rate-hike-bets-inflation-data-focus-2026-09-07/",updatedAt:U},
{symbol:"BTC",name:"Bitcoin",value:"$79,705",change:"−0.20% · −$159",direction:"down",status:"רציף · 08:02",note:"סביב 80 אלף",source:"נתוני שוק",sourceUrl:"https://www.google.com/finance/quote/BTC-USD",updatedAt:U},
{symbol:"ETH",name:"Ethereum",value:"$2,498.82",change:"−0.26% · −$6.57",direction:"down",status:"רציף · 08:02",note:"ירידה קלה",source:"נתוני שוק",sourceUrl:"https://www.google.com/finance/quote/ETH-USD",updatedAt:U}
],meta:{updatedAt:U,locale:"he-IL",edition:"מהדורת בוקר · בחירות, הורמוז, ספורט וטכנולוגיה",contentPolicy:"כל כתבות המהדורה הוחלפו; ארכיון המבזקים בלבד נשמר"},polls:[kan,ch13,walla],scores:[
{id:"f1-monza-20260906-final",league:"פורמולה 1",dateLabel:"06.09",teams:["קימי אנטונלי","ג׳ורג׳ ראסל"],score:["1","2"],state:"final",status:"סופי",outcome:"אנטונלי זינק 19 וניצח",scorers:"פער 3.857 שניות",source:"Formula 1",sourceUrl:"https://www.formula1.com/en/latest/article/antonelli-beats-russell-to-italian-grand-prix-win-with-stunning-comeback-drive.15WtFEBT5JEe4drdeO88t2",winner:"home",verifiedAt:U,verifiedLabel:"אומת 08:02"},
{id:"arsenal-chelsea-20260906-final",league:"פרמייר ליג",dateLabel:"06.09",teams:["ארסנל","צ׳לסי"],score:["2","1"],state:"final",status:"סופי",scorers:"האברץ 25, אודגור 50; רוג׳רס 2",source:"The Guardian",sourceUrl:"https://www.theguardian.com/football/live/2026/sep/06/arsenal-v-chelsea-premier-league-live",winner:"home",verifiedAt:U,verifiedLabel:"אומת 08:02"},
{id:"everton-united-20260906-final",league:"פרמייר ליג",dateLabel:"06.09",teams:["אברטון","מנצ׳סטר יונייטד"],score:["2","2"],state:"final",status:"סופי",outcome:"שוויון בתוספת הזמן",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/soccer/maitland-niles-screamer-earns-everton-2-2-draw-with-man-utd-2026-09-06/",winner:"draw",verifiedAt:U,verifiedLabel:"אומת 08:02"},
{id:"juve-milan-20260906-final",league:"סרייה א׳",dateLabel:"06.09",teams:["יובנטוס","מילאן"],score:["1","1"],state:"final",status:"סופי",scorers:"גאטי 92; סיסה 69",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/soccer/gatti-rescues-point-juventus-1-1-draw-with-ac-milan-2026-09-06/",winner:"draw",verifiedAt:U,verifiedLabel:"אומת 08:02"},
{id:"mainz-hamburg-20260906-final",league:"בונדסליגה",dateLabel:"06.09",teams:["מיינץ","המבורג"],score:["5","0"],state:"final",status:"סופי",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/soccer/mainz-thrash-hamburg-augsburg-go-top-with-win-frankfurt-2026-09-06/",winner:"home",verifiedAt:U,verifiedLabel:"אומת 08:02"},
{id:"alcaraz-paul-20260906-final",league:"US Open",dateLabel:"06.09",teams:["קרלוס אלקראס","טומי פול"],score:["3","0"],state:"final",status:"סופי",scorers:"6:4, 6:3, 6:4",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/tennis/alcaraz-outguns-paul-reach-us-open-quarter-finals-2026-09-06/",winner:"home",verifiedAt:U,verifiedLabel:"אומת 08:02"},
{id:"shelton-tsitsipas-20260906-final",league:"US Open",dateLabel:"06.09",teams:["בן שלטון","סטפנוס ציציפאס"],score:["3","0"],state:"final",status:"סופי",scorers:"6:2, 6:3, 6:4",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/tennis/shelton-stops-tsitsipas-sets-up-alcaraz-showdown-us-open-2026-09-07/",winner:"home",verifiedAt:U,verifiedLabel:"אומת 08:02"},
{id:"redsox-orioles-20260906-final",league:"MLB",dateLabel:"06.09",teams:["בוסטון רד סוקס","בולטימור אוריולס"],score:["3","1"],state:"final",status:"סופי",outcome:"שמירה 400 לצ׳פמן",source:"Reuters",sourceUrl:"https://www.reuters.com/sports/baseball/aroldis-chapman-earns-400th-save-as-red-sox-sweep-orioles--flm-2026-09-06/",winner:"home",verifiedAt:U,verifiedLabel:"אומת 08:02"}
],socialPulse:[],videos:[]};
window.NEWS_FEED.deepDives[0].wordCount=analysis.trim().split(/\s+/).length;
})();
